// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    var app;
    app = window || {};
    if (app.constants == null) {
      app.constants = {};
    }
    app.constants = _.extend(app.constants, {
      directions: ["LEFT", "RIGHT", "UP"],
      canvasXBlock: 45,
      canvasYBlock: 20,
      canvasX: $(document).width() - 30
    });
    return app.constants = _.extend(app.constants, {
      canvasY: app.constants.canvasX * app.constants.canvasYBlock / app.constants.canvasXBlock,
      directions: ["LEFT", "RIGHT", "UP"]
    });
  });

}).call(this);
